### ISSUE TITLE
What's the license on this code?

### ISSUE THREAD

**Issue by mxbi** [MLWave/Online-Random-Bit-Regression-FTRL#1]
Hi,

I was planning to make a repository with an algorithm based on this one, and I was wondering if there is a specific license for this work for me to follow or if you want attribution in a specific form. I wouldn't want to pass off any of the excellent work you have done as my own :smile:

**Comment by MLWave** [comment]
Hi, the original license for the FTRL part of the code is "DO WHATEVER THE FUCK YOU WANT"-licensed: http://www.wtfpl.net/

This code has no license, but you can treat as MIT. Or "do whatever you want" :).

Attribution would be nice (at least attribute the papers I used these ideas from).

Thanks!
